version: '3.8'

services:
  backup-tools-go:
    image: nicodwik/backup-tools-go:1.0 #change this
    container_name: backup-tools-go
    environment:
      # BACKUP_OUTPUT_PATH: "/backups"
      COMPRESSION_LEVEL: "1"
      CRON_EXPRESSION: "0 15 * * * *"
      # INPUT_BASE_PATH: "/data"
    volumes:
      - PATH_TO_BACKUP_OUTPUT_FOLDER:/backups" #change this
      - PATH_TO_BACKUP_SOURCE_FOLDER:/data #change this
